version: "3.0"

services:
  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    restart: always

  elastic:
    container_name: "elastic"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    expose:
      - 9200
    environment:
      - discovery.type=single-node
