name: Service UGC

on:
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ maxtix.python-version }}

      - name: Create directories
        run: |
          mkdir -p reports/kafka_api/wemake-python-styleguide/
          mkdir -p reports/kafka_api/mypy/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  wemake-python-styleguide flake8-html mypy
      - name: Lint with wemake-python-styleguide
        run: |
          flake8 kafka_api/src --exit-zero --format=html --htmldir=reports/kafka_api/wemake-python-styleguide/
      - name: Lint with mypy
        run: |
          mypy --html-report reports/kafka_api/mypy/ kafka_api/src/* || true
